syntax = "proto3";
package tuxtape.server.database.v1;

import "tuxtape/common/v1/kernel.proto";
import "tuxtape/common/v1/vulnerability.proto";

// The main service for tuxtape-server. This is used to get, create, and update
// resources within the TuxTape database.
service DatabaseService {
  // Get `Vulnerability`s from the database that affect at least one `KernelRelease`.
  rpc GetVulnerabilities(GetVulnerabilitiesRequest) returns (GetVulnerabilitiesResponse);
  // Get `VulnerabilityInstances` associated with the provided `Vulnerability`s by their IDs.
  rpc GetVulnerabilityInstances(GetVulnerabilityInstancesRequest) returns (GetVulnerabilityInstancesResponse);
  // Get a `KernelSource` from the database.
  rpc GetKernelSource(GetKernelSourceRequest) returns (GetKernelSourceResponse);
  // Get all `KernelRelease`s which are affected by the provided `VulnerabilityInstance` IDs.
  rpc GetAffectedKernelReleases(GetAffectedKernelReleasesRequest) returns (GetAffectedKernelReleasesResponse);
  // Put a kernel into the database.
  // Once received, tuxtape-server will dispatch a `BuildKernelRequest` to
  // the next available tuxtape-kernel-builder.
  rpc CreateKernel(CreateKernelRequest) returns (CreateKernelResponse);
}

// Get `Vulnerability`s from the database that affect at least one `KernelRelease`.
message GetVulnerabilitiesRequest {}

// The response to a `GetVulnerabilitiesRequest`.
message GetVulnerabilitiesResponse {
  // The `Vulnerability`s that matched the parameters in the request.
  // Will be empty if no matches are found.
  repeated tuxtape.common.v1.Vulnerability vulnerabilities = 1;
}

// Get `VulnerabilityInstances` associated with the provided `Vulnerability`s by their IDs.
message GetVulnerabilityInstancesRequest {
  // The database IDs for the `Vulnerability`s you are requesting.
  repeated int32 vulnerability_ids = 1;
}

// The response to a `GetVulnerabilityInstancesRequest`.
message GetVulnerabilityInstancesResponse {
  // `VulnerabilityInstance`s that matched the request's `Vulnerability` database IDs.
  repeated tuxtape.common.v1.VulnerabilityInstance vulnerability_instances = 1;
}

// Request the `KernelSource` for a `KernelRelease`.
message GetKernelSourceRequest {
  // The database ID for the `KernelRelease` you are requesting a `KernelSource` for.
  int32 kernel_release_id = 1;
}

// The response to a `GetKernelSourceRequest`.
message GetKernelSourceResponse {
  // Will be null if no `KernelSource` matched the request.
  optional tuxtape.common.v1.KernelSource kernel_source = 1;
}

// Get all `KernelRelease`s which are affected by the provided `VulnerabilityInstance` IDs.
message GetAffectedKernelReleasesRequest {
  // The IDs for the `VulnerabilityInstance`s you are requesting `KernelRelease`s for.
  repeated int32 vulnerability_instance_ids = 1;
}

// The response to a `GetAffectedKernelReleasesRequest`.
message GetAffectedKernelReleasesResponse {
  // A tuple of a `VulnerabilityInstance` and the `KernelRelease` that is affected by it.
  message AffectedKernelRelease {
    // The database ID for the `VulnerabilityInstance` that is affected.
    int32 vulnerability_instance_id = 1;
    // The `KernelRelease` that is affected by the provided `VulnerabilityInstance`.
    tuxtape.common.v1.KernelRelease kernel_release = 2;
  }

  // The `KernelRelease`s that are affected by the provided `VulnerabilityInstance`s.
  repeated AffectedKernelRelease kernel_releases = 1;
}

// Request to put a new kernel into the database.
message CreateKernelRequest {
  tuxtape.common.v1.KernelRelease kernel_release = 1;
  // The source of the kernel you wish to add to the database.
  tuxtape.common.v1.KernelSource kernel_source = 2;
}

// The response to a `CreateKernelRequest`.
message CreateKernelResponse {}
