[package]
name = "tuxtape-database-bridge"
version = "0.1.0"
edition = "2024"

[dependencies]
diesel = { version = "2.2", features= ["postgres", "sqlite", "returning_clauses_for_sqlite_3_35" ]}
libsqlite3-sys = { version = "0.29", features = ["bundled"] }
diesel_migrations = "2.2"

[build-dependencies]
dsync = "0.1"
diesel = { version = "2.2", features= ["postgres", "sqlite" ]}
